### ISSUE TITLE
Clustercat dies without an error message

### ISSUE THREAD

**Issue by oroszgy** [jonsafari/clustercat#3]
Hi, first of all thanks for the great library!

I am trying to use your tool on a quite big Hungarian corpus (almost 5G with about 700M tokens) but I am unable to make it work. When I start the tool (`./bin/clustercat --verbose --in ./mycorpus --out clusters.tsv`), it runs for a while without printing out anything, then about 2 minutes it stops leaving an empty cluster file. However if I run the tool on the first 1000 lines of the corpus it works smoothly. Do you have any idea what could go wrong?

**Comment by jonsafari** [comment]
Thanks!
It's hard to say exactly without access to the corpus.  How much memory do you have on the machine?  Does it work with a specified number of clusters (say, 400)?  Is the corpus formatted as one sentence per line, already tokenized, lowercased, no HTML/XML tags, etc?
For reference, I've run ClusterCat on the same scale of corpus for English, Russian, and German, and even 2.5 billion tokens for English, and it worked fine.  Sometimes memory can be the limiting factor, so you could keep an eye on that with htop or something similar.

**Comment by oroszgy** [comment]
Thanks for the answer! 

Starting the process, it starts eating up the memory until it reaches ~5GB, then the whole things just suddenly dies. I think that the memory should not be the problem, since the VM has more than 8 GB RAM. The corpus is tokenized and contains one sentence per line. It is not lowercased, but it would be quite strange if this would be the problem. It should not contain any XML tags, but I'll check it again. Could such a thing cause the issue?

**Comment by oroszgy** [comment]
Cleaned up the corpus, but the process still dies. I've just found out that it has `-1` return code:

```bash
$ echo $?                                                      
255
```

**Comment by jonsafari** [comment]
To see if it's a problem with not enough memory, can you try running it on a server with maybe 64GB of RAM or more?
To see if it's a problem with malformed/unexpected input, can you try successively bisecting the dataset and see if it dies on a specific line?
Assuming the dataset is not publicly available, you could also try uploading the data to something like dropbox or google drive, and I could try training on that dataset.

**Comment by oroszgy** [comment]
@jonsafari thanks for the answer, and sorry for leaving this issue open for so long, I am currently regenerating the dataset, and will experiment with it. Will keep you updated.

**Comment by jonsafari** [comment]
@oroszgy Feel free to reopen this issue whenever you'd like.
