### ISSUE TITLE
Using perplexity to find the optimal number of clusters

### ISSUE THREAD

**Issue by usptact** [jonsafari/clustercat#6]
The clustercat package returns a perplexity measure once it has finished working on a dataset. I am wondering whether it is a good idea to run an optimizer (e.g. BayesOpt) to find the optimal or close to optimal number of clusters. Is this bad idea? If, yes, why?

**Comment by jonsafari** [comment]
It makes perfect sense, and is something I thought of also.  But in practice what happens is that in general the more clusters you have the better your perplexity gets, up to a limit.  But a downstream task sometimes gives better results with fewer classes (eg. when used in conjunction with word types).  So the optimal number of classes often depends on your task.
